import { NextPage } from 'next';
import Head from 'next/head';

import SectionTitle from '../components/SectionTitle';
import TextBlock from '../components/TextBlock';
import { LeftSection, RightSection } from '../components/layout/ColumnSection';
import { LeftColumn, RightColumn } from '../components/layout/Columns';
import * as Content from '../data/content/projects';

export const pTypography =
  'text-white text-base leading-5 sm:leading-snug sm:text-lg font-light';
export const pTypography_purple = 'text-purple-400 font-semibold';

type LinkType = {
  title: string;
  link: string;
};

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Projects | Jack B</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>☘️</text></svg>"
        />
      </Head>
      <LeftColumn>
        <LeftSection>
          <SectionTitle
            white={Content.ProjectsInfo.title!.white}
            purple={Content.ProjectsInfo.title!.purple}
          />
          <TextBlock textSections={Content.ProjectsInfo.body} />
        </LeftSection>
      </LeftColumn>
      <RightColumn>
        <RightSection>
          <SectionTitle purple="All" white="Projects" />
          <TextBlock
            classOptions="lg:max-w-xs"
            textSections={Content.SideBar.body}
          />
          <TextBlock textSections={Content.ProjectsList.body} />
        </RightSection>
      </RightColumn>
    </>
  );
};

const LinkGrid: React.FC<{ links: LinkType[] }> = ({ links }) => {
  return (
    <div className={`w-full flex flex-wrap py-1`}>
      {links.map(({ title, link }, idx) => (
        <a
          href={link}
          key={idx}
          className="pr-2 text-base font-light leading-5 text-left text-white transition-colors duration-100 ease-in-out sm:leading-snug sm:text-lg hover:text-purple-200"
        >
          {title}
        </a>
      ))}
    </div>
  );
};

export default Projects;
